language: node_js
node_js:
  - "11"

services:
  - docker

install:
  - curl -sL https://ibm.biz/idt-installer | bash

script:
  - docker build --rm -t "us.icr.io/dalehille/webapp:${TRAVIS_COMMIT}" .
  - if [ -n "${TRAVIS_TAG}" ]; then docker tag us.icr.io/dalehille/webapp:${TRAVIS_COMMIT} us.icr.io/dalehille/webapp:${TRAVIS_TAG}; fi
  - docker images
  - ./build/process-template.sh kubernetes/webapp/resource.yaml >/tmp/resource.yaml

before_deploy:
  - ibmcloud login -r us-south --apikey ${IBMCLOUD_API_KEY}
  - ibmcloud cr region-set us-south
  - ibmcloud cr login
  # - docker login -u="${QUAY_ID}" -p="${QUAY_TOKEN}" us.icr.io

deploy:
  # Deploy alpha builds
  - provider: script
    script: bash build/push.sh
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$
  - provider: releases
    file: /tmp/resource.yaml
    skip_cleanup: true
    draft: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$
    api_key:
      secure: "${GITHUB_TOKEN}"

  # Deploy released builds
  - provider: script
    script: bash build/push.sh
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: releases
    file: /tmp/resource.yaml
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    api_key:
      secure: "${GITHUB_TOKEN}"
