apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    version: "{{TRAVIS_COMMIT}}"
    razee.io/git-repo: "{{{GIT_REMOTE}}}"
    razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
  labels:
    razee/watch-resource: "lite"
  name: webapp
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
        razee/watch-resource: "lite"
      name: webapp
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
      containers:
      - env:
        - name: APP_VERSION
          value: "{{TRAVIS_COMMIT}}"
        image: "us.icr.io/dalehille/webapp:{{TRAVIS_TAG}}"
        imagePullPolicy: Always
        name: webapp
        ports:
        - containerPort: 3333
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 80Mi
          limits:
            cpu: 500m
            memory: 256Mi
